### ISSUE TITLE
Add Content to README.md

### ISSUE THREAD

**Issue by tolik518** [StefanGreve/dtui#10]
The README.md file for the project is currently blank. Populate it with relevant information. This will help users and contributors understand the purpose and functionality of the project.

**Comment by StefanGreve** [comment]
That's a fair point. When I envisioned this project it escaped my attention that the Discord staff is actively going out of their way to ban accounts that use third-party clients for instant messaging. As it currently stands, I don't have any plans to continue working on this project for the time being. That being said, I may pick up this project again in the distant future and pivot this client in another direction, perhaps toward Matrix? Though I barely know anyone personally who uses that, which is why it's not high on my priority list of things to work on.

**Comment by tolik518** [comment]
Thank you for providing that context. It's understandable that you're not planning to actively develop the project at this time.
However, creating a README.md could still be beneficial for others who might find value in your work, even if it's no longer actively worked on or maintained.
It can serve as a valuable resource and learning tool for those interested in similar projects
Moreover, it can showcase your technical. expertise and thoughtful approach to your potential employers in the future.
That way, your project can continue to have a positive impact, even if you're not actively working on it.
